name: Build Vue
on:
  pull_request:
    types:
      - closed
    branches:
      - main

  build_vue:
    if_merged:
      if: github.event.pull_request.merged
      runs-on: ubuntu-latest
      name: Build Vue
      steps:
      - uses: actions/checkout@v2
      - id: Build-Vue
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          username: 'Lenni009'
          reponame: 'RewardChanceCalculator'
          token: ${{ secrets.GITHUB_TOKEN }}